# Generated by Django 2.2.19 on 2022-08-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220821_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='amountingredient',
            name='recipe',
            field=models.ManyToManyField(related_name='Recipe_amount', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='recipes.AmountIngredient'),
        ),
    ]
