# Generated by Django 2.2.19 on 2022-08-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220822_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='amountingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Recipe_amount', to='recipes.Recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
    ]
